---
- name: Create a VM from a template
  hosts: all
  connection: local
  gather_facts: no
  vars_files:
  - vars/vars.yml
  tasks:
  - name: Clone the template
    vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: False
      name: "{{ name }}"
      template: "{{ vmtemplate }}"
      datacenter: "[Office-Team]"
      folder: "{{ folder }}"
      state: poweredon
      disk:
          - size_gb: "{{ disk_size }}"
            type: thin
            datastore: "{{ datastore }}"      
      networks:
        - name: VM Network
          type: dhcp
      hardware:
          memory_mb: "{{ vm_memory }}"
      wait_for_ip_address: True
      state: present

- name: sleep for 100 seconds and continue with play
  wait_for:
    timeout: 100
  delegate_to: localhost

- name: Workwith Ubuntu Server
  hosts: 192.168.69.46
  remote_user: ha.quoc.anh
  become_user: root
  become: true
  connection: local
  gather_facts: no
  vars_files:
  - vars/vars.yml
  tasks:
  - name: Update Packet
    command: apt-get update
  - name: Install NGINX
    apt:
      name: "{{ packages }}"
      state: latest
  - name: Start NGINX service after install
    service:
      name: nginx
      state: started