- hosts: all
  become_user: root
  become: true
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: Start Service NGINX
      service:
        name: nginx
        state: started