---
- name: Create a VM from a template
  hosts: all
  connection: local
  gather_facts: no
  vars_files:
  - vars/vars.yml
  tasks:
  - name: Provide information about vCenter
    vmware_about_facts:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_user }}'
      password: '{{ vcenter_pass }}'
    delegate_to: localhost
    register: vcenter_about_info