---
- name: Create a VM from a template
  hosts: Vcenter
  connection: local
  gather_facts: no
  vars_files:
  - vars/vars.yml
  tasks:
  - name: Clone the template
    vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: False
      name: "{{ name }}"
      template: "{{ vmtemplate }}"
      datacenter: "[Office-Team]"
      folder: "{{ folder }}"
      state: poweredon
      disk:
          - size_gb: "{{ disk_size }}"
            type: thin
            datastore: "{{ datastore }}"      
      networks:
        - name: VM Network
          type: dhcp
      hardware:
          memory_mb: "{{ vm_memory }}"
      wait_for_ip_address: True
      state: present

- name: Workwith Centos Server
  hosts: Centos7
  remote_user: ha.quoc.anh
  become_user: root
  become: true
  connection: local
  gather_facts: no
  vars_files:
  - vars/vars.yml
  
  pre_tasks:
    - name: Wait for port 22 to become open on the host, don't start checking for 10 seconds
      wait_for:
        port: 22
        host: Centos7
        search_regex: OpenSSH
        delay: 60
        
  tasks:
  - name: Update Packet
    yum:
      name: '*'
      state: latest
  - name: Install NGINX
    yum:
      name: nginx
      state: latest
  - name: Start NGINX service after install
    service:
      name: nginx
      state: started