---
- name: Create a VM from a template
  hosts: all
  connection: local
  gather_facts: no
  tasks:
  - name: Configure IP address on ESX host
    vmware_vmkernel_ip_config:
      hostname: 192.168.69.42
      username: administrator@vsphere.local
      password: Aa@123456
      vmk_name: VMtest_qa
      ip_address: 192.168.69.48
      subnet_mask: 255.255.255.0
    delegate_to: localhost
