---
- name: Check Resouce
  hosts: all
  connection: local
  gather_facts: no
  vars_files:
  - vars/vars.yml
  tasks:
  - name: Gather vmware host facts from vCenter
    vmware_host_facts:
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      esxi_hostname: "{{ esxhost }}"
    delegate_to: localhost
    register: host_facts
    - debug: var=host_facts