---
- name: Create a VM from a template
  hosts: all
  connection: local
  gather_facts: no
  tasks:
  - name: Clone the template
    vmware_guest:
      hostname: 192.168.69.42
      username: administrator@vsphere.local
      password: Aa@123456
      validate_certs: False
      name: testvm_2
      template: "[Template][192.168.69.46] Ubuntu 16.04"
      datacenter: "[Office-Team]"
      folder: /[Office-Team]/vm
      state: poweredon
      disk:
          - size_gb: 60
            type: thin
            datastore: "[Office-Team]"
            folder: "/[Office-Team]/vm"
        networks:
        - name: VM Network
          type: dhcp
        hardware:
          memory_mb: 4096
        wait_for_ip_address: True
        state: present
      register: newvm