---
- name: Create a VM from a template
  hosts: all
  connection: local
  gather_facts: no
  tasks:
  - name: Clone the template
    vmware_guest:
      hostname: 192.168.69.42
      username: administrator@vsphere.local
      password: Aa@123456
      validate_certs: False
      name: vmqa
      template: template: "[Template][192.168.69.46] Ubuntu 16.04"
      datacenter: "[Office-Team]"
      folder: "/[Office-Team]/vmqa"
      state: poweredon
      wait_for_ip_address: yes